---
title: "MBEMMI Scripts & Datasets"
author: "Jian Cao, Paul Beaumont"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 1. Read Raw QCEW Data


### 1.1 Read CSV Files from BLS
<div style="color:DarkBlue; background-color: rgba(0, 0, 0, 0.0470588); text-align:left; vertical-align: middle; padding-left: 20px; padding-bottom: 10px; padding-top: 10px; padding-right: 20px;">
**Script**: `./R/read_bls_qcew.R`

**Object**: Reads each csv file in `./data/BLS/` as a data.frame, puts data.frames in a list and saves the list as a Rds file `./data/raw_bls_qcew.Rds`.

**Output**: `./data/raw_bls_qcew.Rds`
</div><br>


### 1.2 Read CSV Files from DEO
<div style="color:DarkBlue; background-color: rgba(0, 0, 0, 0.0470588); text-align:left; vertical-align: middle; padding-left: 20px; padding-bottom: 10px; padding-top: 10px; padding-right: 20px;">
**Script**: `./R/read_deo_qcew.R`

**Object**: Reads each csv file in `./data/DEO/` as a data.frame, puts data.frames in a list and saves the list as a Rds file `./data/raw_deo_qcew.Rds`.

**Output**: `./data/raw_deo_qcew.Rds`
</div><br>


## 2. Preprocess QCEW Data

### 2.1 Preprocess BLS Data
<div style="color:DarkBlue; background-color: rgba(0, 0, 0, 0.0470588); text-align:left; vertical-align: middle; padding-left: 20px; padding-bottom: 10px; padding-top: 10px; padding-right: 20px;">
**Script**: `./R/preprocess_bls_qcew.R`

**Object**: Reads Rds file `./data/raw_bls_qcew.Rds`, organizes data into time series, saves as Rds file `./data/data_bls_qcew.Rds`.

**Output**: `./data/data_bls_qcew.Rds`
</div><br>


### 2.2 Preprocess DEO Data
<div style="color:DarkBlue; background-color: rgba(0, 0, 0, 0.0470588); text-align:left; vertical-align: middle; padding-left: 20px; padding-bottom: 10px; padding-top: 10px; padding-right: 20px;">
**Script**: `./R/preprocess_deo_qcew.R`

**Object**: Reads Rds file `./data/raw_deo_qcew.Rds`, organizes data into time series, saves as Rds file `./data/data_deo_qcew.Rds`.

**Output**: `./data/data_deo_qcew.Rds`
</div><br>

### 2.3 Merge BLS and DEO Data
<div style="color:DarkBlue; background-color: rgba(0, 0, 0, 0.0470588); text-align:left; vertical-align: middle; padding-left: 20px; padding-bottom: 10px; padding-top: 10px; padding-right: 20px;">
**Script**: `./R/preprocess_data.R`

**Object**: Reads Rds files `./data/raw_bls_qcew.Rds` and `./data/raw_deo_qcew.Rds`, transforms DEO dataset to BLS data's format, computes five-digit level, saves as Rds file `./data/qcew_ready.Rds`. Handles two-digit industries and save as `./data/qcew_2digit_fixed.Rds`.

**Output**: `./data/qcew_ready.Rds` and `./data/qcew_2digit_fixed.Rds`
</div><br>


## 3. Random Suppression
<div style="color:DarkBlue; background-color: rgba(0, 0, 0, 0.0470588); text-align:left; vertical-align: middle; padding-left: 20px; padding-bottom: 10px; padding-top: 10px; padding-right: 20px;">
**Script**: `./R/suppression.R`

**Object**: Reads Rds file `./data/qcew_2digit_fixed.Rds`, applies random primary suppression and secondary suppression, generates `n = 50` randomly suppressed QCEW datasets, puts them in a list and saves the list as Rds file `./data/qcew_rnd_suppression.Rds`.

**Output**: `./data/qcew_rnd_suppression.Rds`
</div><br>

## 4. Multiple Imputation
<div style="color:DarkBlue; background-color: rgba(0, 0, 0, 0.0470588); text-align:left; vertical-align: middle; padding-left: 20px; padding-bottom: 10px; padding-top: 10px; padding-right: 20px;">
**Script**: `./R/PSI.R`, `./R/MBEMMI_20210929.R`, `./R/BMMI.R`, and `./R/EMB.R`

**Object**: Reads Rds file `./data/qcew_rnd_suppression.Rds`, applies PSI-MBEMMI/BMMI/EMB methods, generates `m = 10` imputed datasets for each randomly suppressed QCEW dataset, puts them in a list and saves as Rds file `./data/QCEW_imputations_20211006.Rds`

**Output**: `./data/QCEW_imputations_20211006.Rds`
</div><br>